# Unbalanced npbootstrap coverage oracle (M84 T5) ------------------------------
#
# Asserts the committed n_rep >= 2000 unbalanced sweep fixture
# (`fixtures/npbootstrap-unbalanced-coverage-oracle.rds`, generated by
# `data-raw/m84-npbootstrap-unbalanced-coverage.R`) against:
#   AC4  the ohyama2025 Fig. 2 NBOOT plot-read coverage at three near-nominal cells,
#        within the pre-registered +-0.02 plot-read band; tail errors recorded.
#   GP6  the few-clusters / many-raters dip (k=10, n=10) sits BELOW the near-nominal
#        cells -- the known failure axis the paper names (p. 595).
# Reading a committed fixture (not re-running the sweep) is the reproducibility
# contract: the generator + seeds regenerate it from scratch.

skip_if_not(
  file.exists(test_path(
    "fixtures",
    "npbootstrap-unbalanced-coverage-oracle.rds"
  )),
  "unbalanced coverage fixture not yet generated"
)
oracle <- readRDS(test_path(
  "fixtures",
  "npbootstrap-unbalanced-coverage-oracle.rds"
))

test_that("the fixture is the full n_rep >= 2000 unbalanced sweep over the four cells", {
  expect_setequal(names(oracle), c("A_10_2", "A_25_5", "A_50_5", "D_10_10"))
  for (nm in names(oracle)) {
    expect_gte(oracle[[nm]]$n_rep, 2000L)
    expect_gte(oracle[[nm]]$b_boot, 999L)
    # The MCAR-deletion validity + resample guards leave the vast majority usable.
    expect_gt(oracle[[nm]]$n_ok, 0.9 * oracle[[nm]]$n_rep)
  }
})

test_that("coverage matches the ohyama Fig. 2 NBOOT plot-read within +-0.02 (AC4)", {
  for (nm in c("A_10_2", "A_25_5", "A_50_5")) {
    x <- oracle[[nm]]
    expect_lt(abs(x$coverage_icc1 - x$plot_read), x$band)
  }
})

test_that("tail errors are recorded and reconcile with coverage (AC4)", {
  for (nm in names(oracle)) {
    x <- oracle[[nm]]
    expect_equal(
      x$coverage_icc1,
      1 - x$lower_tail - x$upper_tail,
      tolerance = 1e-8
    )
  }
})

test_that("the few-clusters/many-raters cell dips below the near-nominal cells (GP6)", {
  # ohyama p. 595: NBOOT (like SEARLE) drops to ~0.90 at k=10, n >= 5. The dip cell
  # must sit clearly below the near-nominal high-k/low-n cells -- the known
  # under-coverage axis, not a flat line.
  near_nominal <- min(
    oracle$A_10_2$coverage_icc1,
    oracle$A_25_5$coverage_icc1,
    oracle$A_50_5$coverage_icc1
  )
  expect_lt(oracle$D_10_10$coverage_icc1, near_nominal)
  expect_lt(oracle$D_10_10$coverage_icc1, 0.93)
})
