# M103 -- the reducer-stage degeneracy aborts name a `ci_method` only after
# running that method on the caller's own data.
#
# M93 gave the two `mc_ci()` guards a lazily-evaluated `hint`; the four
# reducer-stage guards had none, so the 2026-08-03 hotfix could only DELETE the
# untrue `ci_method` names from three of them. What this file pins is that the
# names are back and that each one was earned: verified by running the method,
# on the data in hand, at the seed and resample count the caller's own retry
# would use.
#
# The evidence base is `tests/testthat/fixtures/abort-remedy-sweep.tsv`,
# generated by `data-raw/sweep-abort-remedies.R` -- 210 rows, one per
# (guard, dataset, method), of which 26 datasets actually reach their guard.

# --- the sweep's own generators ----------------------------------------------
#
# Copied from the generator script, deliberately: the AC2 table below rebuilds
# each cell's dataset from the fixture's own `generator`/`n_s`/`n_r`/`seed`/
# `trigger` columns and re-derives the verdict. A copy that drifted from the
# script's original would produce different data and therefore different
# verdicts, which is exactly what that test fails on -- the duplication is
# checked, not trusted.

gen_mse0 <- function(n_s, n_r, jitter_sd = 0, seed = 1) {
  set.seed(seed)
  mu <- stats::rnorm(n_s, 0, 3)
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = rep(mu, each = n_r) + stats::rnorm(n_s * n_r, 0, jitter_sd)
  )
}

gen_ssa0 <- function(n_s, n_r, jitter_sd = 0, seed = 1) {
  set.seed(seed)
  profile <- stats::rnorm(n_r, 0, 3)
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = rep(profile, times = n_s) + stats::rnorm(n_s * n_r, 0, jitter_sd)
  )
}

gen_resample_degenerate <- function(n_s, n_r, n_varying = 2L, seed = 1) {
  set.seed(seed)
  mu <- stats::rnorm(n_s, 0, 3)
  score <- rep(mu, each = n_r)
  for (i in seq_len(min(n_varying, n_s))) {
    idx <- ((i - 1) * n_r + 1):(i * n_r)
    score[idx] <- score[idx] + stats::rnorm(n_r, 0, 1)
  }
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = score
  )
}

gen_se_zero <- function(n_s, n_r, seed = 1) {
  data.frame(
    subject = rep(1:3, each = 2),
    rater = rep(1:2, times = 3),
    score = c(-1.5, -0.5, 0, 0, 0.5, 1.5)
  )
}

oneway_ests <- function(k_eff) {
  list(
    icc_estimand(unit = "single", k_eff = k_eff, oneway = TRUE),
    icc_estimand(unit = "average", k_eff = k_eff, oneway = TRUE)
  )
}

# Render a condition's message with the RENDERER pinned, not merely observed: a
# pin that depends on how wide the console happened to be, or on whether cli
# decided the terminal could show `ℹ`, is evidence about the environment
# rather than about the message. Width is fixed so nothing hard-wraps, and the
# bullet is fixed to its ASCII form -- which is what testthat renders anyway, and
# what the expected text below is written in.
abort_message <- function(expr) {
  withr::local_options(cli.width = 10000L, cli.unicode = FALSE)
  e <- suppressWarnings(tryCatch(expr, error = function(e) e))
  expect_s3_class(e, "condition")
  conditionMessage(e)
}

first_line <- function(msg) strsplit(msg, "\n", fixed = TRUE)[[1]][[1]]

# The arguments a bullet PROMISES, read out of the message itself rather than
# written down here. A test that re-runs the author's idea of the promised call
# cannot catch a message that promises something else, which is the whole failure
# mode "the promised call is the verified one" exists to prevent.
promised_args <- function(msg, name) {
  hit <- regmatches(
    msg,
    regexpr(paste0(name, " = [0-9]+"), msg)
  )
  if (!length(hit)) {
    return(NULL)
  }
  as.integer(sub(paste0(name, " = "), "", hit))
}

# The seed a bullet promises, in EITHER form it can take. With no caller seed the
# verification ran under `hint_verify_seed` and the bullet names it as a number;
# with a caller seed it ran under theirs, and the bullet says to run under it
# rather than repeating a value the caller already has. A test that reads only the
# numeric form finds nothing in the second case and re-runs UNSEEDED -- a fresh
# draw, which is the one thing "the promised call is the verified one" exists to
# rule out (M103 review pass 2, G1). So the seed-free form is accepted only when
# the message really does point at the caller's own seed.
promised_seed <- function(msg, caller_seed) {
  named <- promised_args(msg, "seed")
  if (!is.null(named)) {
    return(named)
  }
  expect_match(msg, "run under your", fixed = TRUE)
  caller_seed
}

read_sweep <- function() {
  path <- test_path("fixtures", "abort-remedy-sweep.tsv")
  utils::read.delim(path, comment.char = "#", stringsAsFactors = FALSE)
}

# Rebuild the dataset one fixture row describes. The `trigger` column carries the
# jitter ("exact" / "near") and the resample generator's fixed `n_varying`.
sweep_data <- function(row) {
  switch(
    row$generator,
    gen_mse0 = gen_mse0(
      row$n_s,
      row$n_r,
      jitter_sd = if (grepl("near", row$trigger)) 1e-8 else 0,
      seed = row$seed
    ),
    gen_ssa0 = gen_ssa0(
      row$n_s,
      row$n_r,
      jitter_sd = if (grepl("near", row$trigger)) 1e-8 else 0,
      seed = row$seed
    ),
    gen_resample_degenerate = gen_resample_degenerate(
      row$n_s,
      row$n_r,
      n_varying = 2L,
      seed = row$seed
    ),
    gen_se_zero = gen_se_zero(row$n_s, row$n_r, seed = row$seed),
    stop("unknown generator in the sweep fixture: ", row$generator)
  )
}

# The engine fit `icc()` would hand a guard on this data -- or NULL where this
# platform's glmmTMB dies on the data before any CI-stage guard is reached.
#
# That is not hypothetical, and it is why the tests below fire each guard at its
# OWNING REDUCER rather than through `icc()`, exactly as AC1 already does. On
# `gen_mse0` the Linux and Windows runners raise a raw `NA/NaN gradient
# evaluation` from the point fit while macOS reaches the guard (CI on PR #111,
# 2026-08-05, 5 failures in this file). A test routed through `icc()` on that
# data is therefore evidence about the ENGINE on those platforms and not about
# the guard it names -- it reds where the fit dies, and worse, an assertion that
# a message does NOT contain something passes there for the wrong reason.
engine_or_null <- function(df) {
  suppressWarnings(tryCatch(fit_glmmtmb_oneway(df), error = function(e) NULL))
}

# The hint `icc()` builds for a one-way random call on this data, argument for
# argument with `boundary_hint_for()` in `R/icc.R`. Fired at a reducer this is
# the same promise the dispatch would have passed it, including the engine tier
# when the platform has a fit to give.
icc_hint <- function(
  df,
  invoked,
  engine = engine_or_null(df),
  n_r = 3L,
  seed = 1L,
  boot_samples = 999L
) {
  boundary_method_hint(
    oneway = TRUE,
    multilevel = FALSE,
    replicates = FALSE,
    raters = "random",
    balanced = TRUE,
    type = "agreement",
    type_supplied = FALSE,
    unit = c("single", "average"),
    seed = seed,
    boot_samples = boot_samples,
    mc_samples = 10000L,
    conf_level = 0.95,
    df = df,
    estimands = oneway_ests(n_r),
    n0 = n_r,
    invoked = invoked,
    engine = engine
  )
}

# The bootstrap refit-convergence guard, fired with the engine `icc()` would have
# used -- or, where this platform's fit died on the data, with a refit stub
# returning the all-NA draws such a fit yields. The guard fires on zero converged
# refits either way, which is the condition under test.
fire_bootstrap_guard <- function(
  df,
  hint,
  engine = engine_or_null(df),
  boot_samples = 999L,
  n_r = 3L
) {
  eng <- if (is.null(engine)) {
    list(
      simulate_refit = function(n, seed = NULL) {
        matrix(
          NA_real_,
          nrow = 2L,
          ncol = n,
          dimnames = list(c("subject", "residual"), NULL)
        )
      }
    )
  } else {
    engine
  }
  bootstrap_ci(
    eng,
    oneway_ests(n_r),
    conf_level = 0.95,
    boot_samples = boot_samples,
    seed = 1L,
    hint = hint
  )
}

# --- AC1: every degeneracy guard splices the hint it is handed ----------------

# The six guards, each fired directly at the function that owns it, and each
# handed a hint no verification would ever produce. Firing the OWNER rather than
# `icc()` is deliberate: on some of this data glmmTMB dies with a raw error
# before any CI-stage guard is reached, which would make the test evidence about
# the engine rather than about the guard.
#
# The leading lines are frozen at 703fc1b, the commit that shipped them.
test_that("each of the six degeneracy guards splices a lazily-built hint (AC1)", {
  skip_on_cran()
  synthetic <- c(i = "SYNTHETIC-VERIFIED-BULLET")

  fire <- list(
    list(
      label = "mc_ci: non-finite parameter covariance",
      lead = paste(
        "The Monte-Carlo interval could not be computed: the fitted parameter",
        "covariance is not finite."
      ),
      run = function(hint) {
        rmvn(2L, c(subject = 0), matrix(NA_real_, 1L, 1L), hint = hint)
      }
    ),
    list(
      label = "mc_ci: non-finite draws",
      lead = paste(
        "The Monte-Carlo interval could not be computed: 50% of draws were",
        "non-finite."
      ),
      run = function(hint) {
        mc_interval(
          list(subject = c(1, Inf), residual = c(1, 1)),
          icc_estimand(unit = "single", k_eff = 3, oneway = TRUE),
          hint = hint
        )
      }
    ),
    list(
      label = "bootstrap: refit convergence",
      lead = paste(
        "The bootstrap interval could not be computed: only 0 of 4 refits",
        "converged."
      ),
      run = function(hint) {
        draws <- matrix(
          NA_real_,
          nrow = 2L,
          ncol = 4L,
          dimnames = list(c("subject", "residual"), NULL)
        )
        bootstrap_ci(
          list(simulate_refit = function(n, seed = NULL) draws),
          oneway_ests(3),
          boot_samples = 4L,
          hint = hint
        )
      }
    ),
    list(
      label = "classical: MSE = 0",
      lead = paste(
        "The classical one-way SEARLE exact-F interval is undefined for this",
        "data."
      ),
      run = function(hint) {
        searle_ci(gen_mse0(6, 3), oneway_ests(3), hint = hint)
      }
    ),
    list(
      label = "npbootstrap: observed degeneracy",
      lead = paste(
        "The one-way transformed bootstrap-t interval is undefined for this",
        "data."
      ),
      run = function(hint) {
        npbootstrap_ci(
          gen_ssa0(6, 3),
          oneway_ests(3),
          boot_samples = 99L,
          seed = 1L,
          hint = hint
        )
      }
    ),
    list(
      label = "npbootstrap: degenerate resamples",
      lead = paste(
        "The one-way transformed bootstrap-t interval could not be computed:",
        "128 of 999 resamples were degenerate (SSA = 0 or SE = 0)."
      ),
      run = function(hint) {
        npbootstrap_ci(
          gen_resample_degenerate(30, 2),
          oneway_ests(2),
          boot_samples = 999L,
          seed = 1L,
          hint = hint
        )
      }
    )
  )

  for (site in fire) {
    msg <- abort_message(site$run(synthetic))
    expect_true(grepl("SYNTHETIC-VERIFIED-BULLET", msg, fixed = TRUE))
    expect_identical(first_line(msg), site$lead)

    cnd <- suppressWarnings(tryCatch(
      site$run(character(0)),
      error = function(e) e
    ))
    expect_s3_class(cnd, "intraclass_singular_fit")
    # Without a hint the message is the guard's own text and nothing else.
    expect_false(grepl("SYNTHETIC", conditionMessage(cnd), fixed = TRUE))
  }
})

test_that("a hint is never forced on a call that succeeds (AC1)", {
  skip_on_cran()
  # `hint` is a promise. A successful reduction must never touch it -- the whole
  # cost model of running candidate methods inside an abort depends on it.
  df <- data.frame(
    subject = rep(1:8, each = 3),
    rater = rep(1:3, times = 8),
    score = c(
      5,
      6,
      5,
      2,
      3,
      2,
      8,
      7,
      9,
      4,
      4,
      5,
      6,
      7,
      6,
      3,
      2,
      3,
      9,
      8,
      8,
      5,
      6,
      5
    )
  )
  expect_no_error(
    searle_ci(df, oneway_ests(3), hint = stop("the hint was forced"))
  )
  expect_no_error(
    npbootstrap_ci(
      df,
      oneway_ests(3),
      boot_samples = 99L,
      seed = 1L,
      hint = stop("the hint was forced")
    )
  )
})

# --- AC2: the verdict is the RUN, cell by cell against the sweep --------------

test_that("boundary_method_usable() agrees with the sweep, cell by cell (AC2)", {
  skip_on_cran()
  sweep <- read_sweep()
  reached <- sweep[sweep$reached %in% TRUE, ]
  expect_gt(nrow(reached), 0L)

  # The three DETERMINISTIC-or-cheap methods. `bootstrap` is asserted by
  # `data-raw/check-abort-remedy-verdicts.R` instead: at the 999 refits the
  # fixture was measured under it costs ~17 s per dataset, ~8 min over this
  # table, which is not a per-push cost this suite can carry (M103 implement
  # gate, 2026-08-04).
  cheap <- reached[reached$remedy %in% c("searle", "burch", "npbootstrap"), ]
  expect_gt(nrow(cheap), 0L)

  for (i in seq_len(nrow(cheap))) {
    row <- cheap[i, ]
    got <- boundary_method_usable(
      row$remedy,
      sweep_data(row),
      oneway_ests(row$n_r),
      conf_level = row$conf_level,
      n0 = row$n_r,
      seed = 1L,
      boot_samples = row$boot_samples
    )
    expect_identical(
      got,
      isTRUE(row$remedy_usable),
      info = paste(row$label, row$generator, row$n_s, row$n_r, row$remedy)
    )
  }
})

test_that("the engine-fit rows refuse to verify with no fit in hand (AC2)", {
  skip_on_cran()
  # `bootstrap` and `montecarlo` reduce a fitted model. With no fit they are
  # unavailable rather than assumed usable, so a caller that cannot hand one
  # down names them never.
  for (m in c("bootstrap", "montecarlo")) {
    expect_false(boundary_method_usable(
      m,
      gen_ssa0(6, 3),
      oneway_ests(3),
      conf_level = 0.95,
      n0 = 3,
      engine = NULL
    ))
  }
})

# --- AC3: no guard recommends the method that just failed in it ---------------

test_that("no remedy bullet names the ci_method the caller invoked (AC3)", {
  skip_on_cran()
  # One case per (guard, invoking value). The `gen_ssa0` and resample cases fire
  # through `icc()`, the path a user meets them on. The `gen_mse0` cases cannot:
  # the point fit dies before the guard on some platforms (see `engine_or_null()`
  # above), and an assertion that a message does not name a method would then
  # hold of an engine error rather than of the guard. Those fire at the reducer,
  # handed the hint the dispatch would have built.
  mse0 <- gen_mse0(6, 3)
  cases <- list(
    list(
      method = "bootstrap",
      fire = function() {
        fire_bootstrap_guard(mse0, icc_hint(mse0, "bootstrap"))
      }
    ),
    list(
      method = "searle",
      fire = function() {
        searle_ci(mse0, oneway_ests(3), hint = icc_hint(mse0, "searle"))
      }
    ),
    list(
      method = "burch",
      fire = function() {
        burch_ci(mse0, oneway_ests(3), hint = icc_hint(mse0, "burch"))
      }
    ),
    list(method = "npbootstrap", df = gen_ssa0(6, 3)),
    list(method = "npbootstrap", df = gen_resample_degenerate(30, 2)),
    list(method = "montecarlo", df = gen_ssa0(6, 3))
  )
  for (case in cases) {
    msg <- if (is.null(case$fire)) {
      abort_message(icc(
        case$df,
        score,
        subject,
        rater,
        model = "oneway",
        ci_method = case$method,
        seed = 1L
      ))
    } else {
      abort_message(case$fire())
    }
    # The guard's own leading line is exempt (AC3): `bootstrap_ci()`'s names
    # "bootstrap" by construction, and AC1 freezes it. Everything after it is
    # remedy text.
    remedies <- sub("^[^\n]*\n?", "", msg)
    expect_false(
      grepl(
        paste0("ci_method = \"", case$method, "\""),
        remedies,
        fixed = TRUE
      ),
      info = paste("guard invoked as", case$method)
    )
  }
})

# --- AC4: forcing a hint never re-enters the guard that is forcing it ---------

test_that("verifying burch from a searle abort terminates, not recurses (AC4)", {
  skip_on_cran()
  # `searle_ci()` and `burch_ci()` share `classical_guard_observed()`, so the
  # `searle` abort's own hint runs `burch`, which re-enters that guard. The run
  # carries no hint of its own, so the re-entered guard aborts once and is
  # caught -- one classed condition out, no recursion.
  # Fired at the reducer with the hint the dispatch would have built, so the
  # re-entry is exercised on every platform rather than only where the point fit
  # survives this data (`engine_or_null()` above).
  df <- gen_mse0(6, 3)
  cnd <- suppressWarnings(tryCatch(
    searle_ci(df, oneway_ests(3), hint = icc_hint(df, "searle")),
    error = function(e) e
  ))
  # Reaching this line at all IS the assertion: were the verification run to
  # carry a hint of its own, `searle` would verify `burch`, whose hint would
  # verify `searle`, and the call would never return. What the assertions add is
  # that the one condition to escape is the guard's, raised once.
  expect_s3_class(cnd, "intraclass_singular_fit")
  expect_identical(
    lengths(regmatches(
      conditionMessage(cnd),
      gregexpr("interval is undefined for this data", conditionMessage(cnd))
    )),
    1L
  )
})

test_that("verification passes no hint to any candidate it runs (AC4)", {
  skip_on_cran()
  seen <- list()
  usable_stub <- function() {
    list(
      list(conf.low = 0.1, conf.high = 0.5, std.error = NA_real_),
      list(conf.low = 0.2, conf.high = 0.6, std.error = NA_real_)
    )
  }
  local_mocked_bindings(
    searle_ci = function(df, estimands, conf_level = 0.95, ...) {
      seen[["searle"]] <<- list(...)
      usable_stub()
    },
    burch_ci = function(df, estimands, conf_level = 0.95, ...) {
      seen[["burch"]] <<- list(...)
      usable_stub()
    }
  )
  boundary_method_usable(
    "searle",
    gen_mse0(6, 3),
    oneway_ests(3),
    conf_level = 0.95,
    n0 = 3
  )
  boundary_method_usable(
    "burch",
    gen_mse0(6, 3),
    oneway_ests(3),
    conf_level = 0.95,
    n0 = 3
  )
  # No `hint` argument reaches either reducer at all -- not an empty one, none.
  expect_null(seen[["searle"]]$hint)
  expect_null(seen[["burch"]]$hint)
  expect_false("hint" %in% names(seen[["searle"]]))
  expect_false("hint" %in% names(seen[["burch"]]))
})

# The three shipped messages AC5 freezes, at 703fc1b. The resample guard is
# outside this criterion by construction: `gen_mse0` never reaches it. The
# bootstrap guard reports a glmmTMB CONVERGENCE COUNT, a property of the
# optimizer on this platform's BLAS rather than of the message, so that integer
# alone is normalized on both sides and every other byte is pinned as-is.
normalize_count <- function(x) {
  sub("only [0-9]+ of 999 refits", "only <n> of 999 refits", x)
}

ac5_expected <- list(
  bootstrap = paste0(
    "The bootstrap interval could not be computed: only <n> of 999 refits ",
    "converged.\n",
    "i A refit counts as converged only when every variance component ",
    "it returned is finite.\n",
    "i Inspect the model fit and the data before retrying."
  ),
  searle = paste0(
    "The classical one-way SEARLE exact-F interval is undefined for this ",
    "data.\n",
    "i The F = MSA/MSE pivot is not usable here: MSA = 24.0087, ",
    "MSE = 0.\n",
    "i Inspect the data before retrying."
  ),
  npbootstrap = paste0(
    "The one-way transformed bootstrap-t interval is undefined for this ",
    "data.\n",
    "i The studentized pivot needs a finite log F and a non-zero ",
    "jackknife SE; this data gives log F = Inf and jackknife SE = NaN.\n",
    "i Inspect the data before retrying."
  )
)

# --- AC5: where nothing works, the message is the one that shipped ------------

test_that("no usable candidate leaves the shipped message untouched (AC5)", {
  skip_on_cran()
  # Each guard's `hint` is the REAL one the dispatch would build -- forced, every
  # candidate actually run. It evaluates to nothing on this data because nothing
  # works on it (the sweep's `gen_mse0` cells: 0 usable of every method at all
  # three of these guards). Were verification to accept a method wrongly, a
  # bullet would appear here and these pins would red. Fired at the reducers
  # rather than through `icc()`, which cannot reach them on every platform (see
  # `engine_or_null()`); the end-to-end path is asserted by the companion test
  # below, where the fit survives.
  df <- gen_mse0(6, 3)
  expected <- ac5_expected
  fire <- list(
    bootstrap = function() {
      fire_bootstrap_guard(df, icc_hint(df, "bootstrap"))
    },
    searle = function() {
      searle_ci(df, oneway_ests(3), hint = icc_hint(df, "searle"))
    },
    npbootstrap = function() {
      npbootstrap_ci(
        df,
        oneway_ests(3),
        boot_samples = 999L,
        seed = 1L,
        hint = icc_hint(df, "npbootstrap")
      )
    }
  )
  for (m in names(expected)) {
    expect_identical(
      normalize_count(abort_message(fire[[m]]())),
      expected[[m]],
      info = m
    )
  }
})

test_that("where the fit survives, icc() delivers that same message (AC5)", {
  skip_on_cran()
  # The end-to-end half of the criterion above: on a platform whose glmmTMB
  # survives `gen_mse0`, the message a user actually meets is byte-identical to
  # the one the reducer produced. Where the fit dies first this has nothing to
  # say, and says so rather than passing on an engine error that happens to
  # contain no bullet.
  df <- gen_mse0(6, 3)
  skip_if(
    is.null(engine_or_null(df)),
    "glmmTMB's point fit dies on this data here, before any CI-stage guard"
  )
  for (m in names(ac5_expected)) {
    msg <- abort_message(icc(
      df,
      score,
      subject,
      rater,
      model = "oneway",
      ci_method = m,
      seed = 1L
    ))
    expect_identical(normalize_count(msg), ac5_expected[[m]], info = m)
  }
})

# --- AC3 (cont.): the case self-exclusion is actually load-bearing ------------

test_that("self-exclusion, and not the data, is what silences a method (AC3)", {
  skip_on_cran()
  # Every AC3 case above passes `seed = 1L` and lands on data where the invoked
  # method is not a candidate anyway, so all six stay green with self-exclusion
  # deleted (M103 review, F1). This test isolates the term itself: one dataset,
  # two hints differing ONLY in `invoked`.
  #
  # The case is real rather than contrived. With no caller `seed` the failing run
  # drew from the ambient stream while verification re-runs under the fixed
  # `hint_verify_seed`, so a stochastic method can verify on the very data it
  # just aborted on -- and without the exclusion the message would recommend the
  # call that had just failed.
  set.seed(7)
  n_s <- 12L
  n_r <- 3L
  mu <- stats::rnorm(n_s, 0, 3)
  df <- data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = rep(mu, each = n_r) + stats::rnorm(n_s * n_r, 0, 1)
  )
  df <- df[-1, ] # unbalanced: the branch where npbootstrap is the candidate
  hint_for <- function(invoked) {
    boundary_method_hint(
      oneway = TRUE,
      multilevel = FALSE,
      replicates = FALSE,
      raters = "random",
      balanced = FALSE,
      type = "agreement",
      type_supplied = FALSE,
      unit = list("single"),
      conf_level = 0.95,
      df = df,
      estimands = oneway_ests(3),
      n0 = 3,
      seed = NULL,
      boot_samples = 99L,
      invoked = invoked,
      # No engine: this isolates tier 1, so the only difference between the two
      # calls is the exclusion.
      engine = NULL
    )
  }
  # Invoked as something else, `npbootstrap` verifies and is named...
  expect_true(any(grepl("npbootstrap", hint_for("montecarlo"), fixed = TRUE)))
  # ...and invoked as itself, on the same data, it is named by nothing. Deleting
  # `!identical(method, invoked)` makes these two calls agree, reddening this.
  expect_length(hint_for("npbootstrap"), 0L)
})

# --- AC8: an abort that names nothing stays as fast as its guard -------------

test_that("aborts that name no method are not slowed by verification (AC8)", {
  skip_on_cran()
  # Verification costs what the method costs, and `bootstrap` costs a refit per
  # resample. Before the screen, `icc(gen_mse0(6,3), ci_method = "searle")` took
  # 25.6 s to print a message with no bullet in it: the classical guard's cheap
  # tier is empty by construction (both classical reducers share one guard on the
  # same `ss`), so every such abort fell through to a full 999-refit bootstrap
  # that could not help either. The screen bounds that.
  df <- gen_mse0(6, 3)
  # The criterion measures `icc()`, so where the point fit dies on this data
  # before any guard there is no degeneracy abort here to time -- and the engine's
  # own error would satisfy both assertions for the wrong reason.
  skip_if(
    is.null(engine_or_null(df)),
    "glmmTMB's point fit dies on this data here, before any CI-stage guard"
  )
  for (m in list("searle", "burch", NULL)) {
    call_args <- list(
      df,
      quote(score),
      quote(subject),
      quote(rater),
      model = "oneway"
    )
    if (!is.null(m)) {
      call_args$ci_method <- m
    }
    elapsed <- system.time({
      msg <- abort_message(do.call(icc, call_args))
    })[["elapsed"]]
    label <- if (is.null(m)) "default" else m
    # It named nothing (no method is usable on this data)...
    expect_false(grepl("ci_method = ", msg, fixed = TRUE), info = label)
    # ...so it must not have paid a full bootstrap to find that out.
    expect_lt(elapsed, 5)
  }
})

# --- AC9: the default call is hinted on the same terms as an opt-in one -------

test_that("the DEFAULT icc() call gets the same verified naming (AC9)", {
  skip_on_cran()
  # The engine-fit tier was withheld from the default path at first, on its cost;
  # the M103 review found that left the plain call silent on exactly the data the
  # milestone exists for, while `bootstrap` returns a usable interval on it.
  df <- gen_ssa0(6, 3)
  msg <- abort_message(icc(df, score, subject, rater, model = "oneway"))
  expect_true(grepl('ci_method = "bootstrap"', msg, fixed = TRUE))
  # `montecarlo` is what aborted, so it is never named here (AC3 holds on the
  # default path too).
  expect_false(grepl('ci_method = "montecarlo"', msg, fixed = TRUE))

  # Run exactly what the message promises, with its own named arguments. This
  # call set no seed, so the verification ran under `hint_verify_seed` and the
  # bullet must name it as a number -- an unseeded retry would draw differently.
  seed <- promised_seed(msg, NULL)
  expect_identical(seed, as.integer(hint_verify_seed))
  fit <- icc(
    df,
    score,
    subject,
    rater,
    model = "oneway",
    ci_method = "bootstrap",
    seed = seed,
    boot_samples = promised_args(msg, "boot_samples")
  )
  est <- fit$estimates
  for (i in seq_len(nrow(est))) {
    expect_true(
      boundary_interval_usable(
        list(conf.low = est$conf.low[i], conf.high = est$conf.high[i]),
        divisor = if (identical(est$index[i], "ICC(1)")) 1 else 3,
        n0 = 3
      ),
      info = est$index[i]
    )
  }
})

# --- AC6: the promised call is the verified one ------------------------------

test_that("the gen_ssa0 abort names bootstrap, and that call delivers (AC6)", {
  skip_on_cran()
  # The motivating case. Before M103 a user on this data was told to inspect it;
  # `bootstrap` returns a usable interval on 4 of 4 such datasets in the sweep.
  df <- gen_ssa0(6, 3)
  msg <- abort_message(icc(
    df,
    score,
    subject,
    rater,
    model = "oneway",
    ci_method = "npbootstrap",
    seed = 1L
  ))
  expect_true(grepl("ci_method = \"bootstrap\"", msg, fixed = TRUE))

  # ...and the promise is kept: the same call on the same data, at the seed AND
  # resample count the message itself promises, returns intervals
  # `boundary_interval_usable()` accepts. The caller set a seed here, so the
  # promised seed is theirs and the bullet names no number -- reading only a
  # number would re-run this unseeded.
  seed <- promised_seed(msg, 1L)
  expect_identical(seed, 1L)
  expect_null(promised_args(msg, "seed"))
  fit <- icc(
    df,
    score,
    subject,
    rater,
    model = "oneway",
    ci_method = "bootstrap",
    seed = seed,
    boot_samples = promised_args(msg, "boot_samples")
  )
  est <- fit$estimates
  for (i in seq_len(nrow(est))) {
    expect_true(
      boundary_interval_usable(
        list(conf.low = est$conf.low[i], conf.high = est$conf.high[i]),
        divisor = if (identical(est$index[i], "ICC(1)")) 1 else 3,
        n0 = 3
      ),
      info = est$index[i]
    )
  }
})

test_that("an engine-fit bullet promises a readable seed in both forms (AC6)", {
  skip_on_cran()
  # The two forms the promise can take, pinned so neither can quietly become
  # unreadable. Whichever it is, a reader must be able to reconstruct the seed the
  # verification ran under; a bullet naming no number AND not pointing at the
  # caller's own seed promises a call nobody can reproduce.
  df <- gen_ssa0(6, 3)
  abort_at <- function(...) {
    abort_message(icc(
      df,
      score,
      subject,
      rater,
      model = "oneway",
      ci_method = "npbootstrap",
      ...
    ))
  }
  seeded <- abort_at(seed = 7L)
  # The caller's own seed is what ran, so the bullet points at it rather than
  # repeating the value...
  expect_match(seeded, "run under your", fixed = TRUE)
  expect_null(promised_args(seeded, "seed"))
  expect_identical(promised_seed(seeded, 7L), 7L)
  # ...and with no caller seed the fixed verification seed is named as a number.
  unseeded <- abort_at()
  expect_identical(promised_seed(unseeded, NULL), as.integer(hint_verify_seed))
})

test_that("a two-method engine bullet says whose resample count it names", {
  # Both engine-fit methods usable at once: the bullet then describes TWO runs,
  # and `boot_samples` belongs to only one of them -- `montecarlo` takes none at
  # all. Built directly, because the sweep's data never makes both usable where
  # tier 1 has already failed.
  both <- boundary_engine_hint(
    usable = function(m) TRUE,
    contrast = "the default",
    seed = NULL,
    boot_samples = 999L
  )
  expect_length(both, 1L)
  expect_match(both, "Both runs used", fixed = TRUE)
  expect_match(both, "the bootstrap at", fixed = TRUE)
  expect_match(both, "reproduce them", fixed = TRUE)
  # One method named, one run: the singular wording, and the count reads as its
  # own without needing an owner.
  one <- boundary_engine_hint(
    usable = function(m) identical(m, "bootstrap"),
    contrast = "the default",
    seed = NULL,
    boot_samples = 999L
  )
  expect_match(one, "That run used", fixed = TRUE)
  expect_match(one, "and {.code boot_samples = 199}", fixed = TRUE)
  # And with the caller's own seed, both forms point back at it rather than
  # naming a number.
  expect_match(
    boundary_engine_hint(function(m) TRUE, "the default", seed = 3L),
    "both run under your",
    fixed = TRUE
  )
})
