# M103 -- the reducer-stage degeneracy aborts name a `ci_method` only after
# running that method on the caller's own data.
#
# M93 gave the two `mc_ci()` guards a lazily-evaluated `hint`; the four
# reducer-stage guards had none, so the 2026-08-03 hotfix could only DELETE the
# untrue `ci_method` names from three of them. What this file pins is that the
# names are back and that each one was earned: verified by running the method,
# on the data in hand, at the seed and resample count the caller's own retry
# would use.
#
# The evidence base is `tests/testthat/fixtures/abort-remedy-sweep.tsv`,
# generated by `data-raw/sweep-abort-remedies.R` -- 210 rows, one per
# (guard, dataset, method), of which 26 datasets actually reach their guard.

# --- the sweep's own generators ----------------------------------------------
#
# Copied from the generator script, deliberately: the AC2 table below rebuilds
# each cell's dataset from the fixture's own `generator`/`n_s`/`n_r`/`seed`/
# `trigger` columns and re-derives the verdict. A copy that drifted from the
# script's original would produce different data and therefore different
# verdicts, which is exactly what that test fails on -- the duplication is
# checked, not trusted.

gen_mse0 <- function(n_s, n_r, jitter_sd = 0, seed = 1) {
  set.seed(seed)
  mu <- stats::rnorm(n_s, 0, 3)
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = rep(mu, each = n_r) + stats::rnorm(n_s * n_r, 0, jitter_sd)
  )
}

gen_ssa0 <- function(n_s, n_r, jitter_sd = 0, seed = 1) {
  set.seed(seed)
  profile <- stats::rnorm(n_r, 0, 3)
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = rep(profile, times = n_s) + stats::rnorm(n_s * n_r, 0, jitter_sd)
  )
}

gen_resample_degenerate <- function(n_s, n_r, n_varying = 2L, seed = 1) {
  set.seed(seed)
  mu <- stats::rnorm(n_s, 0, 3)
  score <- rep(mu, each = n_r)
  for (i in seq_len(min(n_varying, n_s))) {
    idx <- ((i - 1) * n_r + 1):(i * n_r)
    score[idx] <- score[idx] + stats::rnorm(n_r, 0, 1)
  }
  data.frame(
    subject = rep(seq_len(n_s), each = n_r),
    rater = rep(seq_len(n_r), times = n_s),
    score = score
  )
}

gen_se_zero <- function(n_s, n_r, seed = 1) {
  data.frame(
    subject = rep(1:3, each = 2),
    rater = rep(1:2, times = 3),
    score = c(-1.5, -0.5, 0, 0, 0.5, 1.5)
  )
}

oneway_ests <- function(k_eff) {
  list(
    icc_estimand(unit = "single", k_eff = k_eff, oneway = TRUE),
    icc_estimand(unit = "average", k_eff = k_eff, oneway = TRUE)
  )
}

# Render a condition's message with the RENDERER pinned, not merely observed: a
# pin that depends on how wide the console happened to be, or on whether cli
# decided the terminal could show `ℹ`, is evidence about the environment
# rather than about the message. Width is fixed so nothing hard-wraps, and the
# bullet is fixed to its ASCII form -- which is what testthat renders anyway, and
# what the expected text below is written in.
abort_message <- function(expr) {
  withr::local_options(cli.width = 10000L, cli.unicode = FALSE)
  e <- suppressWarnings(tryCatch(expr, error = function(e) e))
  expect_s3_class(e, "condition")
  conditionMessage(e)
}

first_line <- function(msg) strsplit(msg, "\n", fixed = TRUE)[[1]][[1]]

read_sweep <- function() {
  path <- test_path("fixtures", "abort-remedy-sweep.tsv")
  utils::read.delim(path, comment.char = "#", stringsAsFactors = FALSE)
}

# Rebuild the dataset one fixture row describes. The `trigger` column carries the
# jitter ("exact" / "near") and the resample generator's fixed `n_varying`.
sweep_data <- function(row) {
  switch(
    row$generator,
    gen_mse0 = gen_mse0(
      row$n_s,
      row$n_r,
      jitter_sd = if (grepl("near", row$trigger)) 1e-8 else 0,
      seed = row$seed
    ),
    gen_ssa0 = gen_ssa0(
      row$n_s,
      row$n_r,
      jitter_sd = if (grepl("near", row$trigger)) 1e-8 else 0,
      seed = row$seed
    ),
    gen_resample_degenerate = gen_resample_degenerate(
      row$n_s,
      row$n_r,
      n_varying = 2L,
      seed = row$seed
    ),
    gen_se_zero = gen_se_zero(row$n_s, row$n_r, seed = row$seed),
    stop("unknown generator in the sweep fixture: ", row$generator)
  )
}

# --- AC1: every degeneracy guard splices the hint it is handed ----------------

# The six guards, each fired directly at the function that owns it, and each
# handed a hint no verification would ever produce. Firing the OWNER rather than
# `icc()` is deliberate: on some of this data glmmTMB dies with a raw error
# before any CI-stage guard is reached, which would make the test evidence about
# the engine rather than about the guard.
#
# The leading lines are frozen at 703fc1b, the commit that shipped them.
test_that("each of the six degeneracy guards splices a lazily-built hint (AC1)", {
  skip_on_cran()
  synthetic <- c(i = "SYNTHETIC-VERIFIED-BULLET")

  fire <- list(
    list(
      label = "mc_ci: non-finite parameter covariance",
      lead = paste(
        "The Monte-Carlo interval could not be computed: the fitted parameter",
        "covariance is not finite."
      ),
      run = function(hint) {
        rmvn(2L, c(subject = 0), matrix(NA_real_, 1L, 1L), hint = hint)
      }
    ),
    list(
      label = "mc_ci: non-finite draws",
      lead = paste(
        "The Monte-Carlo interval could not be computed: 50% of draws were",
        "non-finite."
      ),
      run = function(hint) {
        mc_interval(
          list(subject = c(1, Inf), residual = c(1, 1)),
          icc_estimand(unit = "single", k_eff = 3, oneway = TRUE),
          hint = hint
        )
      }
    ),
    list(
      label = "bootstrap: refit convergence",
      lead = paste(
        "The bootstrap interval could not be computed: only 0 of 4 refits",
        "converged."
      ),
      run = function(hint) {
        draws <- matrix(
          NA_real_,
          nrow = 2L,
          ncol = 4L,
          dimnames = list(c("subject", "residual"), NULL)
        )
        bootstrap_ci(
          list(simulate_refit = function(n, seed = NULL) draws),
          oneway_ests(3),
          boot_samples = 4L,
          hint = hint
        )
      }
    ),
    list(
      label = "classical: MSE = 0",
      lead = paste(
        "The classical one-way SEARLE exact-F interval is undefined for this",
        "data."
      ),
      run = function(hint) {
        searle_ci(gen_mse0(6, 3), oneway_ests(3), hint = hint)
      }
    ),
    list(
      label = "npbootstrap: observed degeneracy",
      lead = paste(
        "The one-way transformed bootstrap-t interval is undefined for this",
        "data."
      ),
      run = function(hint) {
        npbootstrap_ci(
          gen_ssa0(6, 3),
          oneway_ests(3),
          boot_samples = 99L,
          seed = 1L,
          hint = hint
        )
      }
    ),
    list(
      label = "npbootstrap: degenerate resamples",
      lead = paste(
        "The one-way transformed bootstrap-t interval could not be computed:",
        "128 of 999 resamples were degenerate (SSA = 0 or SE = 0)."
      ),
      run = function(hint) {
        npbootstrap_ci(
          gen_resample_degenerate(30, 2),
          oneway_ests(2),
          boot_samples = 999L,
          seed = 1L,
          hint = hint
        )
      }
    )
  )

  for (site in fire) {
    msg <- abort_message(site$run(synthetic))
    expect_true(grepl("SYNTHETIC-VERIFIED-BULLET", msg, fixed = TRUE))
    expect_identical(first_line(msg), site$lead)

    cnd <- suppressWarnings(tryCatch(
      site$run(character(0)),
      error = function(e) e
    ))
    expect_s3_class(cnd, "intraclass_singular_fit")
    # Without a hint the message is the guard's own text and nothing else.
    expect_false(grepl("SYNTHETIC", conditionMessage(cnd), fixed = TRUE))
  }
})

test_that("a hint is never forced on a call that succeeds (AC1)", {
  skip_on_cran()
  # `hint` is a promise. A successful reduction must never touch it -- the whole
  # cost model of running candidate methods inside an abort depends on it.
  df <- data.frame(
    subject = rep(1:8, each = 3),
    rater = rep(1:3, times = 8),
    score = c(
      5,
      6,
      5,
      2,
      3,
      2,
      8,
      7,
      9,
      4,
      4,
      5,
      6,
      7,
      6,
      3,
      2,
      3,
      9,
      8,
      8,
      5,
      6,
      5
    )
  )
  expect_no_error(
    searle_ci(df, oneway_ests(3), hint = stop("the hint was forced"))
  )
  expect_no_error(
    npbootstrap_ci(
      df,
      oneway_ests(3),
      boot_samples = 99L,
      seed = 1L,
      hint = stop("the hint was forced")
    )
  )
})

# --- AC2: the verdict is the RUN, cell by cell against the sweep --------------

test_that("boundary_method_usable() agrees with the sweep, cell by cell (AC2)", {
  skip_on_cran()
  sweep <- read_sweep()
  reached <- sweep[sweep$reached %in% TRUE, ]
  expect_gt(nrow(reached), 0L)

  # The three DETERMINISTIC-or-cheap methods. `bootstrap` is asserted by
  # `data-raw/check-abort-remedy-verdicts.R` instead: at the 999 refits the
  # fixture was measured under it costs ~17 s per dataset, ~8 min over this
  # table, which is not a per-push cost this suite can carry (M103 implement
  # gate, 2026-08-04).
  cheap <- reached[reached$remedy %in% c("searle", "burch", "npbootstrap"), ]
  expect_gt(nrow(cheap), 0L)

  for (i in seq_len(nrow(cheap))) {
    row <- cheap[i, ]
    got <- boundary_method_usable(
      row$remedy,
      sweep_data(row),
      oneway_ests(row$n_r),
      conf_level = row$conf_level,
      n0 = row$n_r,
      seed = 1L,
      boot_samples = row$boot_samples
    )
    expect_identical(
      got,
      isTRUE(row$remedy_usable),
      info = paste(row$label, row$generator, row$n_s, row$n_r, row$remedy)
    )
  }
})

test_that("the engine-fit rows refuse to verify with no fit in hand (AC2)", {
  skip_on_cran()
  # `bootstrap` and `montecarlo` reduce a fitted model. With no fit they are
  # unavailable rather than assumed usable, so a caller that cannot hand one
  # down names them never.
  for (m in c("bootstrap", "montecarlo")) {
    expect_false(boundary_method_usable(
      m,
      gen_ssa0(6, 3),
      oneway_ests(3),
      conf_level = 0.95,
      n0 = 3,
      engine = NULL
    ))
  }
})

# --- AC3: no guard recommends the method that just failed in it ---------------

test_that("no remedy bullet names the ci_method the caller invoked (AC3)", {
  skip_on_cran()
  # One case per (guard, invoking value). Each fires through `icc()`, which is
  # the only path a user meets these messages on and the only one that supplies
  # the engine fit the hint's second tier needs.
  cases <- list(
    list(method = "bootstrap", df = gen_mse0(6, 3)),
    list(method = "searle", df = gen_mse0(6, 3)),
    list(method = "burch", df = gen_mse0(6, 3)),
    list(method = "npbootstrap", df = gen_ssa0(6, 3)),
    list(method = "npbootstrap", df = gen_resample_degenerate(30, 2)),
    list(method = "montecarlo", df = gen_ssa0(6, 3))
  )
  for (case in cases) {
    msg <- abort_message(icc(
      case$df,
      score,
      subject,
      rater,
      model = "oneway",
      ci_method = case$method,
      seed = 1L
    ))
    # The guard's own leading line is exempt (AC3): `bootstrap_ci()`'s names
    # "bootstrap" by construction, and AC1 freezes it. Everything after it is
    # remedy text.
    remedies <- sub("^[^\n]*\n?", "", msg)
    expect_false(
      grepl(
        paste0("ci_method = \"", case$method, "\""),
        remedies,
        fixed = TRUE
      ),
      info = paste("guard invoked as", case$method)
    )
  }
})

# --- AC4: forcing a hint never re-enters the guard that is forcing it ---------

test_that("verifying burch from a searle abort terminates, not recurses (AC4)", {
  skip_on_cran()
  # `searle_ci()` and `burch_ci()` share `classical_guard_observed()`, so the
  # `searle` abort's own hint runs `burch`, which re-enters that guard. The run
  # carries no hint of its own, so the re-entered guard aborts once and is
  # caught -- one classed condition out, no recursion.
  cnd <- suppressWarnings(tryCatch(
    icc(
      gen_mse0(6, 3),
      score,
      subject,
      rater,
      model = "oneway",
      ci_method = "searle",
      seed = 1L
    ),
    error = function(e) e
  ))
  # Reaching this line at all IS the assertion: were the verification run to
  # carry a hint of its own, `searle` would verify `burch`, whose hint would
  # verify `searle`, and the call would never return. What the assertions add is
  # that the one condition to escape is the guard's, raised once.
  expect_s3_class(cnd, "intraclass_singular_fit")
  expect_identical(
    lengths(regmatches(
      conditionMessage(cnd),
      gregexpr("interval is undefined for this data", conditionMessage(cnd))
    )),
    1L
  )
})

test_that("verification passes no hint to any candidate it runs (AC4)", {
  skip_on_cran()
  seen <- list()
  usable_stub <- function() {
    list(
      list(conf.low = 0.1, conf.high = 0.5, std.error = NA_real_),
      list(conf.low = 0.2, conf.high = 0.6, std.error = NA_real_)
    )
  }
  local_mocked_bindings(
    searle_ci = function(df, estimands, conf_level = 0.95, ...) {
      seen[["searle"]] <<- list(...)
      usable_stub()
    },
    burch_ci = function(df, estimands, conf_level = 0.95, ...) {
      seen[["burch"]] <<- list(...)
      usable_stub()
    }
  )
  boundary_method_usable(
    "searle",
    gen_mse0(6, 3),
    oneway_ests(3),
    conf_level = 0.95,
    n0 = 3
  )
  boundary_method_usable(
    "burch",
    gen_mse0(6, 3),
    oneway_ests(3),
    conf_level = 0.95,
    n0 = 3
  )
  # No `hint` argument reaches either reducer at all -- not an empty one, none.
  expect_null(seen[["searle"]]$hint)
  expect_null(seen[["burch"]]$hint)
  expect_false("hint" %in% names(seen[["searle"]]))
  expect_false("hint" %in% names(seen[["burch"]]))
})

# --- AC5: where nothing works, the message is the one that shipped ------------

test_that("no usable candidate leaves the shipped message untouched (AC5)", {
  skip_on_cran()
  # Fired through `icc()`, so each guard's `hint` is the REAL one -- forced,
  # every candidate actually run. It evaluates to nothing on this data because
  # nothing works on it (the sweep's `gen_mse0` cells: 0 usable of every method
  # at all three of these guards). Were verification to accept a method wrongly,
  # a bullet would appear here and these pins would red.
  #
  # The expected text is frozen at 703fc1b. The resample guard is outside this
  # criterion by construction: `gen_mse0` never reaches it.
  df <- gen_mse0(6, 3)
  expected <- list(
    bootstrap = paste0(
      "The bootstrap interval could not be computed: only 55 of 999 refits ",
      "converged.\n",
      "i A refit counts as converged only when every variance component ",
      "it returned is finite.\n",
      "i Inspect the model fit and the data before retrying."
    ),
    searle = paste0(
      "The classical one-way SEARLE exact-F interval is undefined for this ",
      "data.\n",
      "i The F = MSA/MSE pivot is not usable here: MSA = 24.0087, ",
      "MSE = 0.\n",
      "i Inspect the data before retrying."
    ),
    npbootstrap = paste0(
      "The one-way transformed bootstrap-t interval is undefined for this ",
      "data.\n",
      "i The studentized pivot needs a finite log F and a non-zero ",
      "jackknife SE; this data gives log F = Inf and jackknife SE = NaN.\n",
      "i Inspect the data before retrying."
    )
  )
  for (m in names(expected)) {
    msg <- abort_message(icc(
      df,
      score,
      subject,
      rater,
      model = "oneway",
      ci_method = m,
      seed = 1L
    ))
    expect_identical(msg, expected[[m]], info = m)
  }
})

# --- AC6: the promised call is the verified one ------------------------------

test_that("the gen_ssa0 abort names bootstrap, and that call delivers (AC6)", {
  skip_on_cran()
  # The motivating case. Before M103 a user on this data was told to inspect it;
  # `bootstrap` returns a usable interval on 4 of 4 such datasets in the sweep.
  df <- gen_ssa0(6, 3)
  msg <- abort_message(icc(
    df,
    score,
    subject,
    rater,
    model = "oneway",
    ci_method = "npbootstrap",
    seed = 1L
  ))
  expect_true(grepl("ci_method = \"bootstrap\"", msg, fixed = TRUE))

  # ...and the promise is kept: the same call, on the same data, at the seed the
  # message names, returns intervals `boundary_interval_usable()` accepts.
  fit <- icc(
    df,
    score,
    subject,
    rater,
    model = "oneway",
    ci_method = "bootstrap",
    seed = 1L
  )
  est <- fit$estimates
  for (i in seq_len(nrow(est))) {
    expect_true(
      boundary_interval_usable(
        list(conf.low = est$conf.low[i], conf.high = est$conf.high[i]),
        divisor = if (identical(est$index[i], "ICC(1)")) 1 else 3,
        n0 = 3
      ),
      info = est$index[i]
    )
  }
})
