# npbootstrap coverage oracle (M75 T4) -----------------------------------------
#
# Asserts the committed n_rep >= 2000 sweep fixture
# (`fixtures/npbootstrap-coverage-oracle.rds`, generated by
# `data-raw/m75-npbootstrap-coverage.R`) against:
#   AC3  the ukoumunne2003 Table I exact transformed-bootstrap-t coverage at
#        U10/U30/U50 (0.938 / 0.944 / 0.9395) within the pre-registered +-0.03.
#   AC4  two-sided coverage + lower/upper tail-error recorded per cell; the
#        near-zero tail split is roughly balanced (not a BCa-style skew); and
#        truncated-vs-untruncated widths are both reported (truncated <= untruncated).
#   BC3  the ICC(k) interval inherits ICC(1) coverage rep-by-rep (exact identity).
#   BC6  the reported (REML) point-outside-interval rate is bounded by the
#        upper-tail error rate at every cell with true rho > 0 (exact logical bound).
# Reading a committed fixture (not re-running the multi-hour sweep) is the
# reproducibility contract: the generator + seeds regenerate it from scratch.

oracle <- readRDS(test_path("fixtures", "npbootstrap-coverage-oracle.rds"))

# Table I exact transformed-bootstrap-t two-sided coverage (ukoumunne2003, n = 10,
# rho = .05), the pre-registered AC3 anchors.
table_i <- c(U10 = 0.938, U30 = 0.944, U50 = 0.9395)

test_that("the coverage fixture is the full n_rep >= 2000 sweep over all seven cells", {
  expect_setequal(names(oracle), c("C1", "C2", "C3", "C4", "U10", "U30", "U50"))
  for (nm in names(oracle)) {
    expect_gte(oracle[[nm]]$n_rep, 2000L)
    expect_gte(oracle[[nm]]$b_boot, 999L)
  }
})

test_that("coverage matches the ukoumunne2003 Table I anchors within +-0.03 (AC3)", {
  for (nm in names(table_i)) {
    expect_lt(abs(oracle[[nm]]$coverage_icc1 - table_i[[nm]]), 0.03)
  }
})

test_that("tail-error is recorded and the near-zero tail split is balanced (AC4)", {
  for (nm in names(oracle)) {
    x <- oracle[[nm]]
    # Two-sided coverage is (approximately) 1 - the two tail errors.
    expect_equal(x$coverage_icc1, 1 - x$lower_tail - x$upper_tail, tolerance = 1e-8)
  }
  # At the near-zero corner the transformed bootstrap-t keeps a roughly EVEN tail
  # split (Table I ~3.25/2.95 at U10), unlike the BCa skew (~2.4/14.2). A gap this
  # small cleanly separates the two; MC noise at n_rep >= 2000 is ~0.4 pp per tail.
  expect_lt(abs(oracle$U10$lower_tail - oracle$U10$upper_tail), 0.03)
})

test_that("truncated-vs-untruncated widths are both reported on a common scale (AC4)", {
  for (nm in names(oracle)) {
    x <- oracle[[nm]]
    expect_true(is.finite(x$median_width_untrunc))
    expect_true(is.finite(x$median_width_trunc))
    # Truncating to [0,1] can only shrink an interval that dips outside it.
    expect_lte(x$median_width_trunc, x$median_width_untrunc + 1e-12)
  }
})

test_that("ICC(k) coverage inherits ICC(1) coverage rep-by-rep (BC3)", {
  for (nm in names(oracle)) {
    x <- oracle[[nm]]
    expect_identical(x$n_disagree_icc1_icck, 0L)
    expect_equal(x$coverage_icck, x$coverage_icc1, tolerance = 1e-12)
  }
})

test_that("the point-outside-interval rate is bounded by the upper-tail error (BC6)", {
  # Every swept cell has true rho > 0, so the reported (REML) point falling outside
  # the interval is a subset of the upper-tail misses (RR02 §3d): an exact bound.
  for (nm in names(oracle)) {
    x <- oracle[[nm]]
    expect_lte(x$point_outside_rate, x$upper_tail)
  }
})
